### PR TITLE
Workflow shits

### PR DESCRIPTION
**Pull request by moxie-coder**
I updated Haxe to the latest ver (4.3.6, instead of 4.3.0 which I'm pretty sure should help with some bugs with the damn workflows)

### CODE REVIEW

**Comment by nebulazorua** [comment]
4.3.6 broke shit with Lime so we cant use that lol

**Comment by moxie-coder** [comment]
> 4.3.6 broke shit with Lime so we cant use that lol

it has been working fine with the workflows on my end from what I've seen

**Comment by nebulazorua** [comment]
> > 4.3.6 broke shit with Lime so we cant use that lol
> 
> it has been working fine with the workflows on my end from what I've seen, I've been doing tests
maybe it works when set to SPECIFICALLY 4.3.6? when set to latest lime was crying about super constructor call shit

**Comment by moxie-coder** [comment]
> > > 4.3.6 broke shit with Lime so we cant use that lol
> > 
> > 
> > it has been working fine with the workflows on my end from what I've seen, I've been doing tests
> 
> maybe it works when set to SPECIFICALLY 4.3.6? when set to latest lime was crying about super constructor call shit and i looked it up and its Lime <8.1.2 on Haxe 4.3.4+ (even tho we set it to 8.1.2 so it SHOULD run fine)

because Latest is Nightly builds (5.0.0 alpha)

**Comment by nebulazorua** [comment]
OH okay that'd explain it

I'll merge once the current workflows on main and this PR pass

**Comment by moxie-coder** [comment]
> OH okay that'd explain it
> 
> I'll merge once the current workflows on main and this PR pass
> 
> (I'd add the unless="linux" back to the lua_allowed thing tho, cus Lua is broken on Linux atm w/ rico's luajit fork, was gonna look at what made linux work on superpower's fork later)

I've got a dual boot setup with Windows & Linux so I could take a look at it (I've got Ubuntu, and Arch)

**Comment by nebulazorua** [comment]
> > OH okay that'd explain it
> > I'll merge once the current workflows on main and this PR pass
> > (I'd add the unless="linux" back to the lua_allowed thing tho, cus Lua is broken on Linux atm w/ rico's luajit fork, was gonna look at what made linux work on superpower's fork later)
> 
> I've got a dual boot setup with Windows & Linux so I could take a look at it (I've got Ubuntu, and Arch)

was gonna ask Crow to help w/ it but if you wanna do it then go ahead, it'd help tbh

i don't have a linux machine beyond a steam deck atm and I dont wanna program on that thing without getting a USB hub n shit first lol

**Comment by moxie-coder** [comment]
for some weird reason, Mac 11 does not seem to wanna work which is strange

**Comment by nebulazorua** [comment]
buildwindows error is likely just due to the fact this is a PR and not the PR itself so i'll ignore that error lol
if buildmac passes i'll merge rn

**Comment by moxie-coder** [comment]
> buildwindows error is likely just due to the fact this is a PR and not the PR itself so i'll ignore that error lol if buildmac passes i'll merge rn

yeah the Windows one seems to just have bugged, and Mac 11 is just in hiatus for god knows what

**Comment by nebulazorua** [comment]
can prob remove 11 and then just go from there

**Comment by moxie-coder** [comment]
> can prob remove 11 and then just go from there

yeah true

**Comment by moxie-coder** [comment]
alright, all of them are done (excluding 11)

**Comment by nebulazorua** [comment]
I'm just gonna remove 11 and then merge

**Pull request merged**
